language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
    - DJANGO='django>=1.4,<1.5'
    - DJANGO='django>=1.5'
matrix:
    exclude:
        -   python: 3.2
            env: DJANGO='django>=1.4,<1.5'
        -   python: 3.3
            env: DJANGO='django>=1.4,<1.5'
install:
  - pip install $DJANGO --use-mirrors
  - pip install . --use-mirrors
  - pip install python-coveralls --use-mirrors
script:
  - coverage run --rcfile=coverage.rc manage.py test ember
after_success:
  - coveralls -c coverage.rc
